import 'package:flutter/material.dart';
import '../models/restaurant.dart';
import '../models/category.dart';

// Categories data
final List<Category> categories = [
  Category('All', Icons.restaurant, true),
  Category('Fast Food', Icons.fastfood, false),
  Category('Local', Icons.local_dining, false),
  Category('Coffee', Icons.coffee, false),
  Category('Pizza', Icons.local_pizza, false),
  Category('Drinks', Icons.local_bar, false),
];

// Sample restaurant data with actual food images from Unsplash
final List<Restaurant> restaurantData = [
  // Fast Food Category
  Restaurant(
    name: 'McDonald\'s',
    cuisine: 'Fast Food',
    rating: 4.1,
    deliveryTime: '15-25 min',
    imageUrl: 'assets/images/restaurant9.jpg',
    distance: '1.1 km away',
    priceRange: '\$',
    closingTime: '1 AM',
  ),
  Restaurant(
    name: 'Burger King',
    cuisine: 'Fast Food',
    rating: 4.0,
    deliveryTime: '10-20 min',
    imageUrl: 'assets/images/restaurant1.jpg',
    distance: '1.5 km away',
    priceRange: '\$',
    closingTime: '12 AM',
  ),
  Restaurant(
    name: 'KFC',
    cuisine: 'Fast Food',
    rating: 4.2,
    deliveryTime: '20-30 min',
    imageUrl: 'assets/images/restaurant2.jpg',
    distance: '2.0 km away',
    priceRange: '\$',
    closingTime: '11 PM',
  ),

  // Pizza Category
  Restaurant(
    name: 'Pizza Paradiso',
    cuisine: 'Italian',
    rating: 4.5,
    deliveryTime: '20-30 min',
    imageUrl: 'assets/images/restaurant5.jpg',
    distance: '0.5 km away',
    priceRange: '\$\$',
    closingTime: '12 AM',
  ),
  Restaurant(
    name: 'Domino\'s Pizza',
    cuisine: 'Italian',
    rating: 4.3,
    deliveryTime: '25-35 min',
    imageUrl: 'assets/images/restaurant3.jpg',
    distance: '1.2 km away',
    priceRange: '\$\$',
    closingTime: '1 AM',
  ),
  Restaurant(
    name: 'Pizza Hut',
    cuisine: 'Italian',
    rating: 4.4,
    deliveryTime: '30-40 min',
    imageUrl: 'assets/images/restaurant4.jpg',
    distance: '1.8 km away',
    priceRange: '\$\$',
    closingTime: '11 PM',
  ),

  // Coffee Category
  Restaurant(
    name: 'Starbucks Coffee',
    cuisine: 'Coffee',
    rating: 4.4,
    deliveryTime: '10-20 min',
    imageUrl: 'assets/images/restaurant8.jpg',
    distance: '0.3 km away',
    priceRange: '\$\$',
    closingTime: '11 PM',
  ),
  Restaurant(
    name: 'Costa Coffee',
    cuisine: 'Coffee',
    rating: 4.3,
    deliveryTime: '8-15 min',
    imageUrl: 'assets/images/restaurant6.jpg',
    distance: '0.6 km away',
    priceRange: '\$\$',
    closingTime: '10 PM',
  ),
  Restaurant(
    name: 'The Coffee Bean',
    cuisine: 'Coffee',
    rating: 4.5,
    deliveryTime: '12-18 min',
    imageUrl: 'assets/images/restaurant7.jpg',
    distance: '0.9 km away',
    priceRange: '\$\$',
    closingTime: '9 PM',
  ),

  // Drinks Category
  Restaurant(
    name: 'The Smoothie Bar',
    cuisine: 'Drinks',
    rating: 4.6,
    deliveryTime: '5-15 min',
    imageUrl: 'assets/images/restaurant10.jpg',
    distance: '0.7 km away',
    priceRange: '\$\$',
    closingTime: '10 PM',
  ),
  Restaurant(
    name: 'Juice World',
    cuisine: 'Drinks',
    rating: 4.4,
    deliveryTime: '8-12 min',
    imageUrl: 'assets/images/restaurant1.jpg',
    distance: '1.1 km away',
    priceRange: '\$',
    closingTime: '9 PM',
  ),
  Restaurant(
    name: 'Fresh Bar',
    cuisine: 'Drinks',
    rating: 4.7,
    deliveryTime: '10-18 min',
    imageUrl: 'assets/images/restaurant2.jpg',
    distance: '1.4 km away',
    priceRange: '\$\$',
    closingTime: '8 PM',
  ),

  // Local Category
  Restaurant(
    name: 'The Gourmet Hub',
    cuisine: 'International',
    rating: 4.8,
    deliveryTime: '20-45 min',
    imageUrl: 'assets/images/restaurant3.jpg',
    distance: '1.2 km away',
    priceRange: '\$\$\$',
    closingTime: '10 PM',
  ),
  Restaurant(
    name: 'Urban Kitchen',
    cuisine: 'Asian Fusion',
    rating: 4.6,
    deliveryTime: '25-40 min',
    imageUrl: 'assets/images/restaurant4.jpg',
    distance: '0.8 km away',
    priceRange: '\$\$\$',
    closingTime: '11 PM',
  ),
  Restaurant(
    name: 'Bistro Central',
    cuisine: 'French',
    rating: 4.9,
    deliveryTime: '30-50 min',
    imageUrl: 'assets/images/restaurant5.jpg',
    distance: '2.1 km away',
    priceRange: '\$\$\$\$',
    closingTime: '9 PM',
  ),
  Restaurant(
    name: 'Sushi Zen',
    cuisine: 'Japanese',
    rating: 4.8,
    deliveryTime: '35-55 min',
    imageUrl: 'assets/images/restaurant6.jpg',
    distance: '1.8 km away',
    priceRange: '\$\$\$',
    closingTime: '10 PM',
  ),
  Restaurant(
    name: 'Spice Route',
    cuisine: 'Indian',
    rating: 4.7,
    deliveryTime: '25-40 min',
    imageUrl: 'assets/images/restaurant7.jpg',
    distance: '1.6 km away',
    priceRange: '\$\$',
    closingTime: '10:30 PM',
  ),
  Restaurant(
    name: 'Thai Palace',
    cuisine: 'Thai',
    rating: 4.5,
    deliveryTime: '30-45 min',
    imageUrl: 'assets/images/restaurant8.jpg',
    distance: '2.3 km away',
    priceRange: '\$\$',
    closingTime: '10 PM',
  ),
];
